# Part 3: Sections 31 through 45 (Simple English Revision Guide)

def get_part3_html():
    return r"""
    <!-- ==================== SECTION 31: EMPLOYEE DATA MODEL ==================== -->
    <div class="page-break"></div>
    <h1 class="section-title"><span class="section-number">31</span> Employee Data Model (What Fields We Store)</h1>
    
    <p>In <code>Employee.java</code>, we store 5 pieces of information for every employee:</p>

    <table>
        <thead>
            <tr>
                <th style="width: 20%;">Field Name</th>
                <th style="width: 20%;">Java Data Type</th>
                <th style="width: 30%;">Database Column</th>
                <th style="width: 30%;">Explanation in Plain English</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><code>id</code></td>
                <td><code>Long</code></td>
                <td><code>BIGINT PRIMARY KEY AUTO_INCREMENT</code></td>
                <td>Unique ID number automatically generated by database (1, 2, 3...).</td>
            </tr>
            <tr>
                <td><code>name</code></td>
                <td><code>String</code></td>
                <td><code>VARCHAR(255)</code></td>
                <td>Full name of the employee (e.g., "Rahul Sharma").</td>
            </tr>
            <tr>
                <td><code>email</code></td>
                <td><code>String</code></td>
                <td><code>VARCHAR(255)</code></td>
                <td>Work email address (e.g., "rahul@gmail.com").</td>
            </tr>
            <tr>
                <td><code>department</code></td>
                <td><code>String</code></td>
                <td><code>VARCHAR(255)</code></td>
                <td>The team they work in (e.g., "IT", "HR", "Finance").</td>
            </tr>
            <tr>
                <td><code>salary</code></td>
                <td><code>Double</code></td>
                <td><code>DOUBLE</code></td>
                <td>Monthly or annual compensation (e.g., 50000.0).</td>
            </tr>
        </tbody>
    </table>

    <!-- ==================== SECTION 32: DATABASE DESIGN ==================== -->
    <h1 class="section-title"><span class="section-number">32</span> Database Design (The Table Schema)</h1>
    
    <p>Our database has one table called <code>employees</code>. Here is how it is structured:</p>

    <div class="diagram-box">
        <div class="diagram-caption">Table: employees</div>
        <p style="font-family: monospace; font-size: 8.5pt; text-align: left; margin: 6px 15px;">
            +------------+---------------+-------------------------------------+<br>
            | Column     | Type          | Key / Notes                         |<br>
            +------------+---------------+-------------------------------------+<br>
            | id         | BIGINT        | PRIMARY KEY, AUTO_INCREMENT         |<br>
            | name       | VARCHAR(255)  | Full Name                           |<br>
            | email      | VARCHAR(255)  | Email Address                       |<br>
            | department | VARCHAR(255)  | Department Name                     |<br>
            | salary     | DOUBLE        | Numeric Salary Amount               |<br>
            +------------+---------------+-------------------------------------+
        </p>
    </div>

    <!-- ==================== SECTION 33: JPA ANNOTATIONS ==================== -->
    <h1 class="section-title"><span class="section-number">33</span> JPA Annotations (What Do Those @ Symbols Mean?)</h1>
    
    <p>In our Java code, you will see several annotations starting with <code>@</code>. Here is what each one does:</p>
    <ul>
        <li><code>@Entity</code>: Tells Spring and Hibernate: <em>"This Java class represents a table in the database."</em></li>
        <li><code>@Table(name = "employees")</code>: Tells Hibernate to name the database table <code>employees</code>.</li>
        <li><code>@Id</code>: Marks the <code>id</code> variable as the Primary Key of the table.</li>
        <li><code>@GeneratedValue(strategy = GenerationType.IDENTITY)</code>: Tells the database to automatically increment the ID (1, 2, 3...) when a new employee is added.</li>
        <li><code>@Repository</code>: Marks <code>EmployeeRepository</code> as a database access interface.</li>
        <li><code>@Service</code>: Marks <code>EmployeeService</code> as a business logic service component.</li>
        <li><code>@RestController</code>: Tells Spring: <em>"This class receives web requests and sends back data as JSON."</em></li>
        <li><code>@CrossOrigin(origins = "*")</code>: Allows web browsers running on any address to call our APIs without being blocked by CORS security.</li>
    </ul>

    <!-- ==================== SECTION 34: REST API DESIGN ==================== -->
    <h1 class="section-title"><span class="section-number">34</span> REST API Design (The 6 Endpoints)</h1>
    
    <p>Our backend provides 6 standard REST API endpoints:</p>

    <table>
        <thead>
            <tr>
                <th style="width: 12%;">Method</th>
                <th style="width: 33%;">Endpoint URL</th>
                <th style="width: 35%;">What It Does</th>
                <th style="width: 20%;">HTTP Status</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><strong>POST</strong></td>
                <td><code>/employees</code></td>
                <td>Creates and saves a new employee</td>
                <td><code>201 Created</code></td>
            </tr>
            <tr>
                <td><strong>GET</strong></td>
                <td><code>/employees</code></td>
                <td>Fetches all employees in a list</td>
                <td><code>200 OK</code></td>
            </tr>
            <tr>
                <td><strong>GET</strong></td>
                <td><code>/employees/{id}</code></td>
                <td>Fetches one employee by their ID number</td>
                <td><code>200 OK</code> / <code>404</code></td>
            </tr>
            <tr>
                <td><strong>PUT</strong></td>
                <td><code>/employees/{id}</code></td>
                <td>Updates details of an existing employee</td>
                <td><code>200 OK</code> / <code>404</code></td>
            </tr>
            <tr>
                <td><strong>DELETE</strong></td>
                <td><code>/employees/{id}</code></td>
                <td>Deletes an employee by ID</td>
                <td><code>200 OK</code> / <code>404</code></td>
            </tr>
            <tr>
                <td><strong>GET</strong></td>
                <td><code>/employees/department/{dept}</code></td>
                <td>Returns all employees in a specific department</td>
                <td><code>200 OK</code></td>
            </tr>
        </tbody>
    </table>

    <!-- ==================== SECTION 35: API REQUEST/RESPONSE EXAMPLES ==================== -->
    <h1 class="section-title"><span class="section-number">35</span> API Request &amp; Response Examples</h1>
    
    <div class="row-2">
        <div class="col-2">
            <p><strong>1. Add Employee (POST /employees):</strong></p>
            <pre><code>// Send this JSON to /employees:
{
  "name": "Rahul",
  "email": "rahul@gmail.com",
  "department": "IT",
  "salary": 50000.0
}

// Server returns (201 Created):
{
  "id": 1,
  "name": "Rahul",
  "email": "rahul@gmail.com",
  "department": "IT",
  "salary": 50000.0
}</code></pre>
        </div>
        <div class="col-2">
            <p><strong>2. View All (GET /employees):</strong></p>
            <pre><code>// Send GET to /employees:
// Server returns (200 OK):
[
  {
    "id": 1,
    "name": "Rahul",
    "email": "rahul@gmail.com",
    "department": "IT",
    "salary": 50000.0
  },
  {
    "id": 2,
    "name": "Priya",
    "email": "priya@gmail.com",
    "department": "HR",
    "salary": 60000.0
  }
]</code></pre>
        </div>
    </div>

    <div class="row-2">
        <div class="col-2">
            <p><strong>3. Update Details (PUT /employees/1):</strong></p>
            <pre><code>// Send this to /employees/1:
{
  "name": "Rahul Sharma",
  "email": "rahul.sharma@gmail.com",
  "department": "IT",
  "salary": 65000.0
}

// Server returns (200 OK):
{
  "id": 1,
  "name": "Rahul Sharma",
  "email": "rahul.sharma@gmail.com",
  "department": "IT",
  "salary": 65000.0
}</code></pre>
        </div>
        <div class="col-2">
            <p><strong>4. Delete (DELETE /employees/1):</strong></p>
            <pre><code>// Send DELETE to /employees/1:
// Server returns (200 OK):
{
  "message": "Employee deleted successfully with ID: 1"
}

// If ID does not exist (404 Not Found):
{
  "message": "Employee not found with ID: 99"
}</code></pre>
        </div>
    </div>

    <!-- ==================== SECTION 36: HTTP STATUS CODES ==================== -->
    <h1 class="section-title"><span class="section-number">36</span> HTTP Status Codes (Quick Revision)</h1>
    
    <ul>
        <li><code>200 OK</code>: Success! Used when fetching (GET), updating (PUT), or deleting (DELETE) works properly.</li>
        <li><code>201 Created</code>: Used specifically when a new employee is created and added to the database.</li>
        <li><code>404 Not Found</code>: Used when you ask for an employee ID that does not exist in the database (like searching ID 999).</li>
        <li><code>500 Internal Server Error</code>: Means the server crashed (e.g., database connection was lost).</li>
    </ul>

    <!-- ==================== SECTION 37: DEPARTMENT FILTERING ==================== -->
    <h1 class="section-title"><span class="section-number">37</span> How Department Filtering Works</h1>
    
    <p>In <code>EmployeeRepository.java</code>, we wrote one simple line:</p>
    <pre><code>List&lt;Employee&gt; findByDepartmentIgnoreCase(String department);</code></pre>
    <p><strong>How does this work without writing SQL?</strong></p>
    <ul>
        <li>Spring Data JPA reads the method name. It sees <code>findBy</code> + <code>Department</code> + <code>IgnoreCase</code>.</li>
        <li>It automatically creates this SQL query behind the scenes:
            <code>SELECT * FROM employees WHERE UPPER(department) = UPPER('IT');</code></li>
        <li>The <code>IgnoreCase</code> part means it doesn't matter if you type "it", "IT", or "It"—it will find all employees in that department!</li>
    </ul>

    <!-- ==================== SECTION 38: SEARCH FUNCTIONALITY ==================== -->
    <h1 class="section-title"><span class="section-number">38</span> How Search Works (Client-Side Search)</h1>
    
    <p>When you type in the search bar on the webpage, how does it find employees so fast?</p>
    <ul>
        <li>When the webpage first loads, JavaScript downloads all employees and keeps them in an array called <code>allEmployees</code> in memory.</li>
        <li>When you type in <code>#searchInput</code>, JavaScript's <code>filterAndRender()</code> checks the query against 4 fields:
            <pre><code>emp.name.toLowerCase().includes(query) ||
emp.email.toLowerCase().includes(query) ||
emp.department.toLowerCase().includes(query) ||
emp.id.toString().includes(query)</code></pre>
        </li>
        <li>Because this filtering happens right inside your browser's memory, the search results update instantly with zero delay!</li>
    </ul>

    <!-- ==================== SECTION 39: DASHBOARD ANALYTICS ==================== -->
    <h1 class="section-title"><span class="section-number">39</span> How Dashboard Statistics Are Calculated</h1>
    
    <p>The 4 cards at the top of the webpage are calculated by <code>updateStats()</code> in <code>app.js</code>:</p>
    <ol>
        <li><strong>Total Employees:</strong> <code>employees.length</code> (e.g., 5).</li>
        <li><strong>Active Departments:</strong> Uses a JavaScript <code>Set</code> to count only unique departments:
            <code>new Set(employees.map(e => e.department)).size</code>.</li>
        <li><strong>Total Payroll:</strong> Uses JavaScript <code>.reduce()</code> to add up all salaries:
            <code>employees.reduce((sum, e) => sum + (e.salary || 0), 0)</code>.</li>
        <li><strong>Average Salary:</strong> Divides total payroll by total employee count:
            <code>Math.round(totalPayroll / totalCount)</code>.</li>
    </ol>

    <!-- ==================== SECTION 40: TESTING ARCHITECTURE ==================== -->
    <h1 class="section-title"><span class="section-number">40</span> Testing Architecture (How We Test)</h1>
    
    <p>We test our application using <strong>Spring Boot Test</strong> and <strong>MockMvc</strong> in <code>EmployeeControllerTest.java</code>.</p>
    <ul>
        <li>Before each test runs, <code>employeeRepository.deleteAll()</code> clears the database so every test starts fresh and clean.</li>
        <li>The tests run against an isolated in-memory test database (<code>jdbc:h2:mem:testdb</code>) defined in <code>application-test.properties</code>. This ensures testing never touches or deletes real data.</li>
    </ul>

    <!-- ==================== SECTION 41: TEST CASES ==================== -->
    <h1 class="section-title"><span class="section-number">41</span> All 6 Automated Test Cases Explained</h1>
    
    <table>
        <thead>
            <tr>
                <th style="width: 10%;">ID</th>
                <th style="width: 25%;">Test Method</th>
                <th style="width: 45%;">What It Tests</th>
                <th style="width: 20%;">Result</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><strong>TC-01</strong></td>
                <td><code>testAddEmployee()</code></td>
                <td>Sends a POST request to add "Rahul" (IT, 50000). Verifies status 201 and non-null ID.</td>
                <td><span class="badge badge-implemented">PASSED</span></td>
            </tr>
            <tr>
                <td><strong>TC-02</strong></td>
                <td><code>testGetAllEmployees()</code></td>
                <td>Saves 2 employees and sends GET /employees. Verifies list has size 2.</td>
                <td><span class="badge badge-implemented">PASSED</span></td>
            </tr>
            <tr>
                <td><strong>TC-03</strong></td>
                <td><code>testGetEmployeeById()</code></td>
                <td>Saves an employee, gets it by ID. Verifies the returned name matches.</td>
                <td><span class="badge badge-implemented">PASSED</span></td>
            </tr>
            <tr>
                <td><strong>TC-04</strong></td>
                <td><code>testUpdateEmployee()</code></td>
                <td>Sends PUT /employees/{id} to change salary to 65000. Verifies updated salary.</td>
                <td><span class="badge badge-implemented">PASSED</span></td>
            </tr>
            <tr>
                <td><strong>TC-05</strong></td>
                <td><code>testGetEmployeesByDepartment()</code></td>
                <td>Saves 2 IT employees and 1 HR employee. Calls /department/IT. Verifies only the 2 IT employees come back.</td>
                <td><span class="badge badge-implemented">PASSED</span></td>
            </tr>
            <tr>
                <td><strong>TC-06</strong></td>
                <td><code>testDeleteEmployee()</code></td>
                <td>Deletes an employee. Verifies delete success message, then checks that fetching that ID returns 404 Not Found.</td>
                <td><span class="badge badge-implemented">PASSED</span></td>
            </tr>
        </tbody>
    </table>

    <!-- ==================== SECTION 42: WHY MOCKMVC? ==================== -->
    <h1 class="section-title"><span class="section-number">42</span> Why MockMvc?</h1>
    
    <p>Normally, to test a website, you have to start the server, open a browser, click buttons, and check if it worked. This is slow and tedious.</p>
    <p><strong>MockMvc</strong> allows Java to pretend it is a web browser. It sends fake HTTP requests directly to the controller inside memory. It tests URL paths, status codes, and JSON responses in less than 3 seconds!</p>

    <!-- ==================== SECTION 43: POSTMAN TESTING GUIDE ==================== -->
    <h1 class="section-title"><span class="section-number">43</span> Postman Testing Guide</h1>
    
    <p>The repository includes a ready-made Postman collection file: <code>Employee_Management_API.postman_collection.json</code>.</p>
    <p><strong>How to use it:</strong></p>
    <ol>
        <li>Open Postman on your computer.</li>
        <li>Click <strong>Import</strong> and select <code>Employee_Management_API.postman_collection.json</code>.</li>
        <li>You will see all 6 requests pre-configured with headers and JSON bodies. Just click <strong>Send</strong>!</li>
    </ol>

    <!-- ==================== SECTION 44: ERROR HANDLING ==================== -->
    <h1 class="section-title"><span class="section-number">44</span> Error Handling (What Happens When an ID Doesn't Exist?)</h1>
    
    <p>In <code>EmployeeService.java</code>, when you try to update or delete an employee with an ID that doesn't exist:</p>
    <pre><code>.orElseThrow(() -> new RuntimeException("Employee not found with ID: " + id));</code></pre>
    <p>In <code>EmployeeController.java</code>, this error is caught with a <code>try-catch</code> block. The controller sends back an HTTP <code>404 Not Found</code> status with a friendly JSON message:</p>
    <pre><code>{ "message": "Employee not found with ID: 99" }</code></pre>

    <!-- ==================== SECTION 45: SECURITY ANALYSIS ==================== -->
    <h1 class="section-title"><span class="section-number">45</span> Security Analysis (Current State vs Future Production)</h1>
    
    <table>
        <thead>
            <tr>
                <th style="width: 30%;">Security Feature</th>
                <th style="width: 35%;">Current State in Project</th>
                <th style="width: 35%;">What Should Be Added for Production</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><strong>User Login</strong></td>
                <td>None (all endpoints are open).</td>
                <td>Spring Security with login passwords and JWT tokens.</td>
            </tr>
            <tr>
                <td><strong>Permissions (RBAC)</strong></td>
                <td>Anyone can delete or edit employees.</td>
                <td>Only users with <code>ROLE_ADMIN</code> can delete; others can only view.</td>
            </tr>
            <tr>
                <td><strong>CORS</strong></td>
                <td><code>@CrossOrigin(origins = "*")</code> allows any website.</td>
                <td>Restrict to the company's official domain name only.</td>
            </tr>
            <tr>
                <td><strong>Database Password</strong></td>
                <td>Written in <code>application.properties</code>.</td>
                <td>Hide passwords using environment variables.</td>
            </tr>
        </tbody>
    </table>
    """
